import { resolve } from 'node:path'
import { createFixtureCinematicProject, expect, test } from './provider-fixture'
import { arkFrameResponseFixture } from '../src/features/generation/fixtures/ark-analysis.fixture'

test('confirms panoramic and serial nine-grid requests and restores every image from IndexedDB', async ({ page }) => {
  const requests: Array<Record<string, unknown>> = []
  await page.route('https://fixture.seedream.invalid/api/v3/images/generations', async route => {
    const body = route.request().postDataJSON()
    requests.push(body)
    await route.fulfill({ json: { data: [{ url: `https://media.fixture.invalid/image-analysis-${requests.length}.png`, size: body.size }] } })
  })
  await createFixtureCinematicProject(page)
  await page.getByRole('button', { name: '适配画布' }).click()
  const scene = page.getByRole('button', { name: '场景设定', exact: true })
  await scene.click()
  const tools = page.getByRole('toolbar', { name: '图片创作工具' })
  await tools.getByRole('button', { name: '全景', exact: true }).click()
  const panorama = page.getByRole('dialog', { name: '720全景' })
  await expect(panorama).toContainText('不保证等距柱状投影')
  await panorama.getByRole('button', { name: '取消' }).click()
  expect(requests).toHaveLength(0)
  await tools.getByRole('button', { name: '全景', exact: true }).click()
  await panorama.getByRole('textbox', { name: '分析描述' }).fill('清晨古桥')
  await panorama.getByRole('button', { name: '确认生成' }).click()
  await expect(scene.locator('img')).toHaveAttribute('src', 'https://media.fixture.invalid/image-analysis-1.png')
  expect(String(requests[0]!.prompt)).toContain('equirectangular')
  const [width, height] = String(requests[0]!.size).split('x').map(Number)
  expect(width / height).toBe(2)
  await tools.getByRole('button', { name: '全景预览' }).click()
  await expect(page.getByRole('dialog', { name: '场景设定 720全景预览' })).toBeVisible()
  await page.getByRole('button', { name: '关闭全景预览' }).click()

  const composer = page.getByRole('region', { name: '场景设定 生成参数' })
  await composer.getByRole('textbox', { name: '提示词' }).fill('清晨古桥 /九宫格')
  await page.getByRole('option', { name: /九宫格分镜预设/ }).click()
  const grid = page.getByRole('dialog', { name: '多机位九宫格' })
  await expect(grid).toContainText('串行 9 次')
  await expect(grid).toContainText('162 积分')
  expect(requests).toHaveLength(1)
  await grid.getByRole('button', { name: '确认生成' }).click()
  await expect.poll(() => requests.length).toBe(10)
  await expect(page.getByText('多机位九宫格结果已保存到项目与生成历史。')).toBeVisible()
  expect(new Set(requests.slice(1).map(request => request.prompt)).size).toBe(9)
  expect(requests.every(request => request.model === 'doubao-seedream-5-0-pro-260628')).toBe(true)
  await expect(page.getByText('已保存', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: '适配画布' }).click()
  await scene.click()
  await page.getByRole('button', { name: '查看 9 张结果' }).click()
  const results = page.getByRole('region', { name: '场景设定 的 9 张结果' })
  await expect(results.locator('img')).toHaveCount(9)
  await expect(results).toHaveCSS('grid-template-columns', /\S+ \S+ \S+/)
})

test('confirms reference lighting correction with a prompt bbox at 721px without touching unsupported tools', async ({ page }) => {
  await page.setViewportSize({ width: 721, height: 778 })
  let submitted: Record<string, unknown> | undefined
  await page.route('https://fixture.seedream.invalid/api/v3/images/generations', async route => {
    submitted = route.request().postDataJSON()
    await route.fulfill({ json: { data: [{ url: 'https://media.fixture.invalid/image-lighting.png', size: submitted!.size }] } })
  })
  await createFixtureCinematicProject(page)
  await page.getByRole('button', { name: '适配画布' }).click()
  await page.getByRole('button', { name: '场景设定', exact: true }).click()
  const composer = page.getByRole('region', { name: '场景设定 生成参数' })
  await composer.getByRole('button', { name: '图片创作模板' }).click()
  await page.getByRole('dialog', { name: '图片创作模板' }).getByRole('button', { name: '电影级光影校正' }).click()
  const dialog = page.getByRole('dialog', { name: '电影级光影矫正' })
  await dialog.getByRole('textbox', { name: '分析描述' }).fill('暖色轮廓光，保留主体身份')
  await dialog.getByRole('checkbox', { name: '指定光影区域' }).check()
  for (const [name, value] of [['左边界', '10'], ['上边界', '20'], ['右边界', '600'], ['下边界', '900']]) await dialog.getByRole('spinbutton', { name }).fill(value!)
  await expect(dialog).toContainText('18 积分')
  const confirm = dialog.getByRole('button', { name: '确认生成' })
  await confirm.scrollIntoViewIfNeeded()
  await expect(confirm).toBeInViewport()
  expect(submitted).toBeUndefined()
  await confirm.click()
  await expect(page.getByRole('button', { name: '场景设定', exact: true }).locator('img')).toHaveAttribute('src', 'https://media.fixture.invalid/image-lighting.png')
  expect(submitted!.image).toEqual([expect.stringMatching(/^https:\/\/media.fixture.invalid\//)])
  expect(submitted!.prompt).toEqual(expect.stringContaining('<bbox>10 20 600 900</bbox>'))
  expect(submitted).not.toHaveProperty('mask')
})

test('uploads a real video fixture for sampled analysis, persists timeline text and reopens the report', async ({ page }) => {
  const requests: Array<Record<string, any>> = []
  await page.route('https://fixture.seedream.invalid/api/v3/chat/completions', async route => {
    requests.push(route.request().postDataJSON())
    await route.fulfill({ json: arkFrameResponseFixture })
  })
  await createFixtureCinematicProject(page)
  await page.getByRole('button', { name: '添加节点' }).click()
  await page.getByRole('menu', { name: '添加节点' }).getByRole('menuitem', { name: '逐帧拉片 本地分析' }).click()
  const node = page.getByRole('region', { name: '逐帧拉片 01 逐帧拉片参数' })
  await node.getByRole('button', { name: '开始拉片' }).click()
  const dialog = page.getByRole('dialog', { name: '逐帧拉片分析' })
  await dialog.getByLabel('上传分析素材').setInputFiles(resolve('e2e/fixtures/video-result.mp4'))
  await expect(dialog.getByRole('checkbox', { name: '音乐维度' })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: '确认分析' })).toBeEnabled()
  expect(requests).toHaveLength(0)
  await dialog.getByRole('button', { name: '确认分析' }).click()
  await expect(node.getByRole('region', { name: '拉片分析结果' })).toContainText('古桥全景')
  expect(requests).toHaveLength(1)
  expect(requests[0]!.messages[1].content[0]).toMatchObject({ type: 'video_url', video_url: { fps: 1, url: expect.stringMatching(/^data:video\/mp4;base64,/) } })
  await expect(page.getByText('已保存', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: '适配画布' }).click()
  await page.getByRole('button', { name: '逐帧拉片 01', exact: true }).click()
  await expect(page.getByRole('region', { name: '拉片分析结果' })).toContainText('摄影机缓慢前推')
  await expect(page.getByRole('link', { name: '下载分析报告' })).toHaveAttribute('download', '逐帧拉片 01-分析.json')
})
