import { createFixtureCinematicProject, expect, test } from './provider-fixture'

test('extracted dock, resources and export overlays keep their entry points and dismiss behavior', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await createFixtureCinematicProject(page)
  for (const [entry, name] of [['打开工具箱', '工具箱'], ['资产管理', '资产管理'], ['素材库', '素材库'], ['角色库', '角色库'], ['历史记录', '历史']]) {
    await page.getByRole('button', { name: entry, exact: true }).click()
    await expect(page.getByRole('complementary', { name, exact: true })).toBeVisible()
    await page.getByRole('button', { name: `关闭${name}面板` }).click()
    await expect(page.getByRole('complementary', { name, exact: true })).toHaveCount(0)
  }
  await page.getByRole('button', { name: '发布与分享' }).click()
  await page.getByRole('menuitem', { name: '导出画布', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '导出画布' })).toContainText('当前视口')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '导出画布' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '发布与分享' })).toBeFocused()
  expect(errors).toEqual([])
})

test('menu and Slash share preset defaults and confirmation focus at 721px without generating on cancel', async ({ page }) => {
  await page.setViewportSize({ width: 721, height: 778 })
  const generated: string[] = []
  page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/images/generations')) generated.push(request.url()) })
  await createFixtureCinematicProject(page)
  await page.getByRole('button', { name: '适配画布' }).click()
  await page.getByRole('button', { name: '场景设定', exact: true }).click()
  const composer = page.getByRole('region', { name: '场景设定 生成参数' })
  await composer.getByRole('button', { name: '图片创作模板' }).click()
  await page.getByRole('dialog', { name: '图片创作模板' }).getByRole('button', { name: '多机位九宫格', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '多机位九宫格' })
  await expect(dialog.getByRole('textbox', { name: '分析描述' })).toBeFocused()
  await expect(dialog.getByRole('combobox', { name: '输出清晰度' })).toHaveValue('1.5K')
  await expect(dialog).toContainText('串行 9 次')
  await expect(dialog).toContainText('162 积分')
  const confirm = dialog.getByRole('button', { name: '确认生成', exact: true })
  await confirm.scrollIntoViewIfNeeded()
  await expect(confirm).toBeInViewport()
  await confirm.focus()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: '关闭多机位九宫格' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await composer.getByRole('textbox', { name: '提示词' }).fill('古桥 /九宫格')
  await page.getByRole('option', { name: /九宫格分镜预设/ }).click()
  await expect(dialog.getByRole('combobox', { name: '输出清晰度' })).toHaveValue('1.5K')
  await expect(dialog.getByRole('textbox', { name: '分析描述' })).toHaveValue('古桥')
  await expect(dialog).toContainText('162 积分')
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  expect(generated).toHaveLength(0)
})

test('Agent preferences and panel lifecycle do not mutate director 3D scene and camera', async ({ page }) => {
  await page.goto('/projects/new')
  await expect(page.getByRole('region', { name: '项目画布' })).toBeVisible()
  await page.getByRole('button', { name: '添加节点', exact: true }).click()
  await page.getByRole('menuitem', { name: '导演台 NEW' }).click()
  const panel = page.getByRole('region', { name: '导演台 01 导演台参数' })
  await expect(panel.getByRole('img', { name: '导演台 01 3D视口' })).toBeVisible()
  await panel.getByRole('button', { name: '添加立方体' }).click()
  await panel.getByRole('tree', { name: '3D对象树' }).getByRole('textbox', { name: '立方体 01名称' }).fill('保留道具')
  await panel.getByRole('button', { name: '顶部视图' }).click()
  await page.getByRole('button', { name: 'Agent', exact: true }).click()
  const agent = page.getByRole('complementary', { name: 'Agent 工作区' })
  await agent.getByRole('textbox', { name: '告诉我下一步要做什么' }).fill('只编辑草稿，不执行')
  await agent.getByRole('button', { name: '新对话', exact: true }).click()
  await agent.getByRole('button', { name: '关闭 Agent' }).click()
  await expect(panel.getByRole('textbox', { name: '保留道具名称' })).toHaveValue('保留道具')
  await expect(panel.getByRole('button', { name: '顶部视图' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByText('已保存', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: '适配画布' }).click()
  await page.getByRole('button', { name: '导演台 01', exact: true }).click()
  await expect(panel.getByRole('textbox', { name: '保留道具名称' })).toHaveValue('保留道具')
  await expect(panel.getByRole('button', { name: '顶部视图' })).toHaveAttribute('aria-pressed', 'true')
})
